services:
  - type: web
    name: salesiq-frontend
    runtime: static
    branch: main
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        sync: false

  - type: web
    name: salesiq-backend
    runtime: node
    plan: free
    branch: main
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URLS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DB_SSL
        value: "true"
      - key: JWT_SECRET
        sync: false
