services:
  - type: static_site
    name: salesiq-frontend
    env: static
    plan: free
    branch: main
    root: client
    buildCommand: npm install && npm run build
    publishPath: build

  - type: web_service
    name: salesiq-backend
    env: node
    plan: free
    branch: main
    root: server
    buildCommand: npm install
    startCommand: npm start
